### ISSUE TITLE
Add comparison with SBE and Chronicle-Wire

### ISSUE THREAD

**Issue by plokhotnyuk** [chronoxor/CppSerialization#1]

**Comment by chronoxor** [comment]
I add SBE to the proto comparison. 

SBE serialization performs very fast, just because its flat simple data model with some serious limitations:

1. It is not easy to manipulate with variable length types. I cannot put `varStringEncoding` type into `<composite>` for Order and Balance structs;
2. Variable data must be declared only at the end of `<sbe:message>` which is top struct and cannot be nested;
3. String manipulations in `<composite>` is limited only with fixed length char fields and no UTF-8 encoding code is generated for C++ (`<type name="symbol" primitiveType="char" length="10" characterEncoding="UTF-8"/>`);
4. SBE collections are limited only with Groups which performs as vector and cannot contain nested `<sbe:message>` as well;
5. Versioning by adding new fields can be done only for `<sbe:message>` and cannot be done for `composite`;

I thinks SBE is a good alternative for old bank FIX/FAST protocol, which is very close to it.

**Comment by chronoxor** [comment]
Unfortunately Chronicle-Wire is a Java only protocol and it is not suitable for C++ proto comparison in CppSerialization project. Perhaps I'll check it in future with Java version of my FastBinaryEncoding proto.
